[global]
interface_name = "enp0s20f0u1u3"

[log]
level = "debug" # info, debug, warn, error, success, trace
type = "pretty" # json, console, pretty

[firewall]
# All incoming connections will be blocked by default
allowed_ports = [22] # Specify ports you want to allow