package tracker

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"log"
	"net"
	"os"
	"strings"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	devstdout "github.com/containerscrew/devstdout/pkg"
	"github.com/containerscrew/ebpfw/dto"
	"github.com/containerscrew/ebpfw/utils"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -type event bpf ./xdp.bpf.c -- -I../headers

// SetDenyPolicy sets the "default deny" policy in the eBPF program.
// If enable is true, incoming traffic is denied by default unless explicitly allowed.
func SetDenyPolicy(enable bool, objs *bpfObjects) {
	var mode uint8 = 0
	if enable {
		mode = 1
	}
	key := uint32(0)
	if err := objs.DenyPolicy.Update(&key, &mode, ebpf.UpdateAny); err != nil {
		log.Printf("Failed to set deny policy: %v", err)
	}
}

// AddAllowedPort adds a port to the allowed ports map in the eBPF program.
func AddAllowedPort(port uint16, objs *bpfObjects) {
	var value uint8 = 1
	if err := objs.AllowedPorts.Update(&port, &value, ebpf.UpdateAny); err != nil {
		log.Printf("Failed to add allowed port: %v", err)
	}
}

func StartNetworkTracking(ctx context.Context) {
	// Retrieve the context data (log and config) from the context
	contextData := dto.GetContextData(ctx)

	config := contextData.Config
	logger := contextData.Log

	// Look up the network interface by name.
	ifaceName := config.Global.InterfaceName
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		logger.Error("lookup network iface",
			devstdout.Argument("iface", ifaceName),
			devstdout.Argument("error", err))
		return
	}

	// Get a list of addresses assigned to the interface
	addrs, err := iface.Addrs()
	if err != nil {
		log.Fatalf("unable to get addresses: %s", err)
		return
	}

	address := fmt.Sprintf("%s", addrs[0])
	// Split the address at the "/" and take the first part
	localIp := strings.Split(address, "/")[0]

	// Load pre-compiled programs into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %s", err)
		return
	}
	defer objs.Close()

	// Attach the program.
	l, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpProg,
		Interface: iface.Index,
	})

	if err != nil {
		logger.Error("could not attach XDP program", err)
		return
	}
	defer l.Close()

	logger.Info("Attached XDP program to iface",
		devstdout.Argument("iface", iface.Name),
		devstdout.Argument("index", iface.Index),
		devstdout.Argument("ip", localIp),
	)

	// Set default deny policy (enable or disable)
	SetDenyPolicy(true, &objs)  // Enable default deny to block incoming traffic by default
	AddAllowedPort(80, &objs)   // Allow HTTP traffic
	AddAllowedPort(443, &objs)  // Allow HTTPS traffic
	AddAllowedPort(8080, &objs) // Allow Nginx on 8080

	// Create a perf reader to read events from the kernel
	reader, err := perf.NewReader(objs.Events, os.Getpagesize())
	if err != nil {
		log.Fatalf("Failed to open perf ring buffer: %v", err)
		return
	}
	defer reader.Close()

	// bpfEvent is generated by bpf2go
	var event bpfEvent
	for {
		// Read an event from the ring buffer
		record, err := reader.Read()
		if err != nil {
			log.Printf("Error reading from perf ring buffer: %v", err)
			continue
		}

		// Parse the raw event data into the bpfEvent struct
		if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.BigEndian, &event); err != nil {
			log.Printf("Error parsing event: %v", err)
			continue
		}

		// Log events
		messageHandler(event, logger)
	}
}

func messageHandler(event bpfEvent, logger *devstdout.CustomLogger) {
	// Determine the protocol as a string
	protocol := utils.GetProtocolType(event.Protocol)

	logger.Info("received new packet",
		devstdout.Argument("source_ip", intToIP(event.Saddr).String()),
		devstdout.Argument("destination_ip", intToIP(event.Daddr).String()),
		devstdout.Argument("source_port", event.Sport),
		devstdout.Argument("destination_port", event.Dport),
		devstdout.Argument("protocol", protocol),
	)
}

// intToIP converts a 32-bit IPv4 number to net.IP
func intToIP(ipNum uint32) net.IP {
	ip := make(net.IP, 4)
	binary.BigEndian.PutUint32(ip, ipNum)
	return ip
}
