package tracker

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"log"
	"net"
	"os"
	"strings"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	devstdout "github.com/containerscrew/devstdout/pkg"
	"github.com/containerscrew/ebpfw/dto"
	"github.com/containerscrew/ebpfw/utils"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -type event bpf ./xdp.bpf.c -- -I../headers

// Helper function to add allowed ports
func addAllowedPort(port uint16, objs *bpfObjects) error {
	portBE := bpf_htons(port) // Convert to network byte order
	var value uint8 = 1
	return objs.AllowedPorts.Put(portBE, value)
}

func StartNetworkTracking(ctx context.Context) {
	// Retrieve the context data (log and config) from the context
	contextData := dto.GetContextData(ctx)

	config := contextData.Config
	logger := contextData.Log

	// Look up the network interface by name.
	ifaceName := config.Global.InterfaceName
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		logger.Error("lookup network iface",
			devstdout.Argument("iface", ifaceName),
			devstdout.Argument("error", err))
		return
	}

	// Get a list of addresses assigned to the interface
	addrs, err := iface.Addrs()
	if err != nil {
		log.Fatalf("unable to get addresses: %s", err)
		return
	}

	address := fmt.Sprintf("%s", addrs[0])
	// Split the address at the "/" and take the first part
	localIp := strings.Split(address, "/")[0]

	// Load pre-compiled programs into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %s", err)
		return
	}
	defer objs.Close()

	// Attach the program.
	l, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpProg,
		Interface: iface.Index,
	})

	if err != nil {
		logger.Error("could not attach XDP program", err)
		return
	}
	defer l.Close()

	logger.Info("Attached XDP program to iface",
		devstdout.Argument("iface", iface.Name),
		devstdout.Argument("index", iface.Index),
		devstdout.Argument("ip", localIp),
	)

	// Apply allowed ports rules
	for _, port := range config.Firewall.AllowedPorts {
		if err := addAllowedPort(uint16(port), &objs); err != nil {
			logger.Warning("Failed to add allowed Port", err)
		}
	}

	// Create a perf reader to read events from the kernel
	reader, err := perf.NewReader(objs.Events, os.Getpagesize())
	if err != nil {
		log.Fatalf("Failed to open perf ring buffer: %v", err)
		return
	}
	defer reader.Close()

	// bpfEvent is generated by bpf2go
	var event bpfEvent
	for {
		// Read an event from the ring buffer
		record, err := reader.Read()
		if err != nil {
			log.Printf("Error reading from perf ring buffer: %v", err)
			continue
		}

		// Parse the raw event data into the bpfEvent struct
		if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.BigEndian, &event); err != nil {
			log.Printf("Error parsing event: %v", err)
			continue
		}

		// Log events
		messageHandler(event, config, logger)
	}
}

func messageHandler(event bpfEvent, config *dto.Config, logger *devstdout.CustomLogger) {
	// Determine the protocol as a string
	protocol := utils.GetProtocolType(event.Protocol)

	// By default, we drop all packets unless allowed
	action := "dropped"

	// Check if the destination port is in the allowed list
	if config.Firewall.DefaultDeny {
		if containsInt(config.Firewall.AllowedPorts, int(event.Dport)) {
			action = "forwarded"
		}
	}

	// Log based on action
	if action == "dropped" {
		logger.Warning(fmt.Sprintf("Packet from IP %s to port %d dropped.", intToIP(event.Saddr), event.Dport))
	} else {
		logger.Debug(fmt.Sprintf("Packet from IP %s to port %d %s.", intToIP(event.Saddr), event.Dport, action),
			devstdout.Argument("protocol", protocol),
		)
	}
}

// intToIP converts a 32-bit IPv4 number to net.IP
func intToIP(ipNum uint32) net.IP {
	ip := make(net.IP, 4)
	binary.BigEndian.PutUint32(ip, ipNum)
	return ip
}

// Helper function to convert uint16 to network byte order
func bpf_htons(port uint16) uint16 {
	return (port>>8)&0xff | (port<<8)&0xff00
}

// Helper function to check if a slice contains an int
func containsInt(slice []int, item int) bool {
	for _, a := range slice {
		if a == item {
			return true
		}
	}
	return false
}
